### ISSUE TITLE
CSS Library choice

### ISSUE THREAD

**Issue by rschragger** [rschragger/MAR#3]
Research which CSS libraries might work and might have good templates for us

**Comment by Artur0705** [comment]
Hey guys! I just found Css frameworks that we can use.
First one is Material and the second one is Tailwind.
In my opinion Material is better then Tailwind. Have a
look at the links provided below and will discuss it later on today.

Material - https://materializecss.com/getting-started.html

Tailwind - https://tailwindcss.com/docs/installation

**Comment by Artur0705** [comment]
Choose to use Material for Css.

https://materializecss.com/getting-started.html
